// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWwfD6GFRRP0nQIQ7eRIoIdijHin2lVj4',
    appId: '1:983100080605:web:dd4ce07605c99fba76f634',
    messagingSenderId: '983100080605',
    projectId: 'eduscript-d7f91',
    authDomain: 'eduscript-d7f91.firebaseapp.com',
    storageBucket: 'eduscript-d7f91.appspot.com',
    measurementId: 'G-PQSN6DZ2GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUU-zvVzpBUlUQ-dqF7x-n_m36R97XFA',
    appId: '1:983100080605:android:e6e5bfaca28955cb76f634',
    messagingSenderId: '983100080605',
    projectId: 'eduscript-d7f91',
    storageBucket: 'eduscript-d7f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xIs7iUN1OWuzmpVKEB31k9mzOe7izDE',
    appId: '1:983100080605:ios:7eb08eda92812c8776f634',
    messagingSenderId: '983100080605',
    projectId: 'eduscript-d7f91',
    storageBucket: 'eduscript-d7f91.appspot.com',
    iosClientId:
        '983100080605-3ds21228u6qct34cpbg1g2o3ungtva5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduscript',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4xIs7iUN1OWuzmpVKEB31k9mzOe7izDE',
    appId: '1:983100080605:ios:3cd263854f2bb8ad76f634',
    messagingSenderId: '983100080605',
    projectId: 'eduscript-d7f91',
    storageBucket: 'eduscript-d7f91.appspot.com',
    iosClientId:
        '983100080605-6kgf9ro4rdcgfthamlq7cv8941ggb0gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduscript.RunnerTests',
  );
}
